name: "Install the action-validator with asdf"
description: "Only exists to not duplicate the hardcoding of the action-validator version"

runs:
  using: "composite"
  steps:
    - name: Install asdf
      uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
    - name: Install action-validator with asdf
      uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      with:
        tool_versions: |
          action-validator latest
