name: "Install the action-validator with asdf"
description: "Only exists to not duplicate the hardcoding of the action-validator version"

runs:
  using: "composite"
  steps:
    - name: Install action-validator with asdf
      uses: asdf-vm/actions/setup@v4
