name: "Install the action-validator with asdf"
description: "Only exists to not duplicate the hardcoding of the action-validator version"

runs:
  using: "composite"
  steps:
    - name: Install action-validator with asdf
      uses: asdf-vm/actions/install@v3
      with:
        tool_versions: |
          action-validator 0.5.1
